### ISSUE TITLE
Exercise MATCH

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#10]
Could you make an exercise with an oppotunity to create text-cards (text 1) or pictures (images 1)  at the top of the screen and also create one more set of text-cards (text 2) or pictures (images 2) at the bottom of the screen. Students must match the top and bottom cards.

**Comment by a34alefeliza** [comment]
How to match cards? What is the action that the student needs to perform in order to match cards?

**Comment by Dashkinru** [comment]
> How to match cards? What is the action that the student needs to perform in order to match cards?
The easiest way I saw it is to drag the bottom cards to the top cards like we do here - pa.read-hand.html
But we need to see all cards at the top and at the bottom at the same time, not only one card at a time like in this exercise mentioned above.

**Comment by Dashkinru** [comment]
Hi! I came across this task. https://wordwall.net/resource/7930817/discussion
I love the way these cards are bright. Is it possible for us to colour our cards?

**Comment by a34alefeliza** [comment]
you have a new ex called MATCH. you can create a "mixed" collection top top cards, and images2/text2 collection for bottom cards. With mixed collection you can mix text and images. See if you like it!

**Comment by a34alefeliza** [comment]
concerning brightness: you suggest changing the background color of the cards on this exercise? Or in general? Consider that if you want a background color you should always use images with a transparent background, otherwise it will look not really nice.

**Comment by Dashkinru** [comment]
Sorry I am not sure that understand you about brightness ... I was thinking to look for an oppotunity to change the colour of the cards in general. I see that our rivals)))) can made colourful cards and backgrounds. Alessandro, please do not get me wrong))) I suggest what I see is appropriate but if it's impossible just tell me. I will look for other choices))

**Comment by Dashkinru** [comment]
> you have a new ex called MATCH. you can create a "mixed" collection top top cards, and images2/text2 collection for bottom cards. With mixed collection you can mix text and images. See if you like it!

text2 doesn't work. I've made a card but don't see it when open exercise.

**Comment by a34alefeliza** [comment]
No worries Dasha, it is ok that you look at competitors and make proposals! This will definetly improve pikimoni...

The problem that I see with colors is the following: if you use text, I can easily give you the opportunity to set a background color (for example gold):
![image](https://user-images.githubusercontent.com/9462653/102281036-7d68d580-3f2e-11eb-8238-984f7414153a.png)

But if you use an image, the background color is the one of the image itself, and I cannot change it. So if the image has white background, then the card's background will be white. I can change the border:
![image](https://user-images.githubusercontent.com/9462653/102281464-4515c700-3f2f-11eb-9267-8f4827c80bac.png)

**Comment by Dashkinru** [comment]
Wow! Great news)) 
And yes, I meant coloured background for text collections. Will ALL text collection have it colour? Or we can choose the collection or exercise?
And is there a possibility for teachers to change different colours (like have 4 main colours to work with) ? Or we can use only one colour like gold?

**Comment by a34alefeliza** [comment]
I was planning to give to the teacher a color palette they can choose from. All cards in the page will have the same color. Teacher can choose the color at lesson time.
PS if you use transparent background for your images, the color will work for image cards too!

**Comment by Dashkinru** [comment]
Cool! So, if you want blue background for cards you can do it in advance or in the lesson, right? 
But also you can leave the cards white.  I think it's fantastic!

**Comment by a34alefeliza** [comment]
ok I'll find the way to do it. What do you think about "mixed" collection? It is promising?

**Comment by a34alefeliza** [comment]
Actually, I suggest closing this issue and create a new one, called "pikimoni colorful" (or similar)

Also Yulia is asking the same for a longtime... putting more colors on pikimoni.

**Comment by Dashkinru** [comment]
Ok! Let's do like that)) But first teach me how to separate the words in text 2. If I use a space - they come together as one word. Hash tag can divide cards. But what can divide the words inside the card?

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/103168804-b8281300-4836-11eb-9f3b-b42d43743074.png)
done, it was an issue on my side. If you are happy, please close this issue. Today I will start working on colors...
