### ISSUE TITLE
add text pa.sort-numbers.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#12]
That's very important to have text cards which we can move creating the right order of the words in a sentence. May be we can add text collection here or make somethning new. It's up to you of course)) But we shall keep in mind that we also need two sets of cards for 2 teams.

**Comment by a34alefeliza** [comment]
Done. Add text and text2 collections to your exercise

**Comment by Dashkinru** [comment]
Thank you for everything!!!

**Comment by Dashkinru** [comment]
If everything is ok and I choose DONE option, shall I assign it to you back? Or click DONE is enough?

**Comment by a34alefeliza** [comment]
done is enough!
