### ISSUE TITLE
Purple colour

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#14]
Hello! Could you add purple, orange and pink colours to the text editing function? Plus double the same colours with empty space inside but with the same colour frames. It's like with the other colours that we have. Hope you understood me))

**Comment by a34alefeliza** [comment]
done. You can check colors here in case you want a different one:
https://www.w3schools.com/colors/colors_groups.asp

**Comment by Dashkinru** [comment]
Hi! That purple is alomst indistinguisable from black. Could you change it for this one, pls ?

DarkViolet | #9400D3

And also I'd be greatful if you could make pink pinkish)) Like this shade 

HotPink | #FF69B4
