### ISSUE TITLE
fix cards in a grid pa.flip3.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#15]
Hello! Could you fix cards here (pa.flip3.html) so that they wouldn't change the grid when you open the right-side panel. Because for many games we need the number of cards vertically and horizontaly to be the same no matter what. So if teachers can themselves build the grid (like, for example, 6 cards horizontaly and 4 cards vertically) it'd be awesome!

**Comment by a34alefeliza** [comment]
I think the easiest is to make a new exercise, using grid collection. With grid, elements are in a fixed position.

**Comment by Dashkinru** [comment]
Did I understand you rightly? You can create a new ex with fixed card positon AND they will be FLIPPED cards.

**Comment by a34alefeliza** [comment]
you can use pa.grid.html template and fix the number of cards for each row.

**Comment by Dashkinru** [comment]
Hooray!!! Thanks!!!
