### ISSUE TITLE
add text collection pa.be-good.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#16]
Hi! Could you create a new exercise on the base of this one pa.be-good.html but with text collections and 3 cards to change? It's for irregular verbs. Like you see a card with GO, click on it  with the magic wond and it becomes WENT click one more time and it becomes GONE.

**Comment by a34alefeliza** [comment]
Done. I have added "Irregular Verbs" exercise to diy. Use text collection.

**Comment by Dashkinru** [comment]
Thanks a lot!!!
С уважением,
Дарья


вс, 29 нояб. 2020 г. в 03:40, Alessandro <notifications@github.com>:

**Comment by Dashkinru** [comment]
Alessandro, hi! Is there a possibility to have more then 1 word-set of cards on the screen? Something like in a TV exercise.
And could you add a frame around the card so that students will accept it rather more as a card, not a single word on the screen?
And one more 😥 Could you make it possible to type not only 1 word but a phrase or a sentence)))?

**Comment by a34alefeliza** [comment]
Hi Dasha, yes no problem. Let me check what I can do.

**Comment by a34alefeliza** [comment]
Hi, done. Use hash as separator.

**Comment by Dashkinru** [comment]
That's great!!! Thank you! I also asked to to have an oppotunity to type out a phrase not only one word. Have you done it too? I tried to separate with space, comma, but I wan't able to do it. Then how?)

**Comment by a34alefeliza** [comment]
use has as separator, and newline for the next set:
![image](https://user-images.githubusercontent.com/9462653/101265587-f22a5b80-3747-11eb-9495-3074c2d352a7.png)

As a general rule from now on, I will always use the same separators unless differently specified

**Comment by Dashkinru** [comment]
Alessandro, I've testes this ex (pa.magic-wand.html) "Irregular verbs" today and found out that children see this box above the card [Meg#she] )))
![image](https://user-images.githubusercontent.com/66912801/102398566-802bff00-3ff0-11eb-98e5-a0d3934dfea7.png)

**Comment by Dashkinru** [comment]
Also, I'd like to ask to make a board for these cards more brighter and thicker. Maybe purple. I think it will be stylish: purple words and purple frame.

**Comment by a34alefeliza** [comment]
ok, it's fixed now.
IMPORTANT: we have a new collection type, called "grid". This is going to be useful in order to design grids where elements have fixed positions. So I changed text into grid. Each grid line is a "mixed" collection where you can have text and images. How does it look? Again, if you are happy with it, close this issue. Thx

**Comment by Dashkinru** [comment]
Wow! It's centered)) Cool! 
You know , I tried to add an image and fail... Can you do that? 
With texts it works well))

**Comment by a34alefeliza** [comment]
now you can!

**Comment by Dashkinru** [comment]
I see! It works well. Also, urls-images work well. But audio and video don't work. Will they? Or in some exercises they won't be accessible?

**Comment by a34alefeliza** [comment]
audio should work. video not yet... still I need to find a nice way to fit it.

**Comment by Dashkinru** [comment]
Somewhere it works, but here doesn't 

pa.lesson5.html
pa.lesson4.html
