### ISSUE TITLE
make text smaller

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#17]
Hi! Could you make the size of a text in the editing part (when we could color it) smaller 3 times maybe? I'll try to attach a printsreen to explain what I mean in a better way.
![image](https://user-images.githubusercontent.com/66912801/100455024-0bd7fd00-30cf-11eb-9575-a42f4bc27915.png)

And at the same time make the textbox bigger when you are typing so that you would be able  to see more text area parallel to typing.

**Comment by a34alefeliza** [comment]
Hi! 3 times smaller is too small, it will be hard to detect colors, specially stokes. I did it half the size.

**Comment by Dashkinru** [comment]
Thank you! It's perfect!!! Sorry for my poor hand-eye))))
С уважением,
Дарья


вс, 29 нояб. 2020 г. в 00:46, Alessandro <notifications@github.com>:
