### ISSUE TITLE
unite seperate collections from Test exercise pa.millionaire.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#20]
Hi! Looking back how much work you've recently done and how many exercises modified, I guess now a could ask you to modify this one pa.millionaire.html
Is it possible to make ONE collection with different test question. Maybe like you've done in Irregular verbs.

**Comment by a34alefeliza** [comment]
with grid collection, we might have this possibility. The easiest is to create a new exercise , and keep the existing exercise as it is.

**Comment by Dashkinru** [comment]
Sure! Do it, pls.

**Comment by a34alefeliza** [comment]
you have a new template (pa.new-millionaire.html) where you can use a grid collection. For each line you can add a text for question and possible answers.

**Comment by Dashkinru** [comment]
I've tried it out. Everything work great!
Is it possible to add using images there?
