### ISSUE TITLE
Just wonder...

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#21]
Alessandro, what do you think if we can create an ex or add this function to an existing one - to build in a link to a video on youtube?

**Comment by a34alefeliza** [comment]
we already have it! )) I Can Read/Videos

**Comment by Dashkinru** [comment]
As I understood, only I, as an administrator, can upload the video or url
there. And is it possible for the teachers to create their own collections
with url videos?

С уважением,
Дарья


вс, 6 дек. 2020 г. в 18:24, Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
Sorry, I Can Sing/Video. Yes, you can create your own url collection. Urls must be in the format https://youtu.be/bebLde5kcqo
Click the "share" button on youtube video and the url will popup.

**Comment by Dashkinru** [comment]
Wicked!!!)))
