### ISSUE TITLE
how to add more separate lines? pa.sort-numbers.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#24]
Is it possible to create as many separate new lines as needed? Like there is one sentence with a task to put in order. But it'd be great to have more lines with more sentnces.
![image](https://user-images.githubusercontent.com/66912801/101959040-a0854380-3c15-11eb-97f0-4d37f80087be.png)

**Comment by a34alefeliza** [comment]
yes it is possible to have multiple lines. But you can sort words only within one sentence. Is that ok?

**Comment by Dashkinru** [comment]
Yes. I don't want to mix the words from different sentences. One line - one
sentence.

вс, 13 дек. 2020 г., 2:42 Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
done. Use newline to split sentences

**Comment by Dashkinru** [comment]
I tested the ex today and found 2 bugs: 
*during the ex when all 3 users were moving the words, these words were moved only on their screens - we don't see each other's changes. 
* text 2 weren't in lines. Thought I don't see that it is necessary now regarding that we can make as many lines for different users as we want. Maybe it's better to remove text2 completely so that not to confuse the users?

**Comment by a34alefeliza** [comment]
fixed. I also removed text2 collection as it is no longer needed.

**Comment by Dashkinru** [comment]
Greate! Thanks!!! The last thing  - could you make the boarders thicker? They may be black. But I'd like the words look more like cards than just words on the screen. Ok?! 
Oh, I forgot that soon we'll be able to make text-cards bright))))
And I've checked the ex. I don't know why but it doesn't work for me.
https://www.loom.com/share/ce9340249e154e11955af4f0eae407d9

**Comment by a34alefeliza** [comment]
mmh... I tried and it works. Can you make sure to refresh both pages (student and teacher) and try again? If it works and you are happy with this ex, please close this issue. Thx

**Comment by Dashkinru** [comment]
Everything works perfect! Thanks!!!
