### ISSUE TITLE
mix a board game and tic tac toe

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#26]
Could you consider to make a new game where the idea will be following:
1. there are 3 lines and 11 squares 
2. they are fixed like in a board game
3. teachers can make text collections like in tic tac toe
4. students will flip the coin and move along the line, clicking on the square where they have to stop and do a task.
5. there are 3 different pieces with which the students will mark their squares (naught, cross, and check-square)
Also, could you make the space between cards smaller?
![image](https://user-images.githubusercontent.com/66912801/101961941-e6dda100-3c1b-11eb-8a04-c9394900a476.png)

![image](https://user-images.githubusercontent.com/66912801/101961793-86e6fa80-3c1b-11eb-95ba-e88b619486a8.png)

**Comment by a34alefeliza** [comment]
with the new "grid" collection you should be able to make most of it. The only missing part are the markers, right?

**Comment by Dashkinru** [comment]
Right.
