### ISSUE TITLE
add text collection to pa.lesson4.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#27]
Could you add a text collection here pa.lesson4.html.
The idea is to type cards and give the students the oppotunity to mark it as right or wrong.

**Comment by a34alefeliza** [comment]
I did a new kind of collection that could solve many problems: it's called "mixed" and you can add either images and/or text (in the same collection). Maybe we should consider using this new collection type wherever it's possible.
![image](https://user-images.githubusercontent.com/9462653/101999294-c37a2b00-3cdb-11eb-83ff-bef5d2130587.png)

**Comment by Dashkinru** [comment]
OK!) I'll keep that in mind. But that's not what I need for this idea. I'll find another solution if you tell me, that it's very difficult or impossible.

**Comment by a34alefeliza** [comment]
what I mean is the following:
![image](https://user-images.githubusercontent.com/9462653/102895322-c5bf5080-4464-11eb-880f-f4f0a5facd1d.png)

My idea is to replace all _img_ and _text_ collections with _mixed_! Mixed can handle both text and images. And the teacher or editor is free to use what is needed for the scope of that lesson. Does it make sense?

**Comment by a34alefeliza** [comment]
done, with mixed collection

**Comment by Dashkinru** [comment]
![image](https://user-images.githubusercontent.com/66912801/103104758-31a6e200-463a-11eb-9bf4-e8139a6a98f1.png)
Great!!!!! How to separate the words?

**Comment by a34alefeliza** [comment]
fixed! If you are happy with it, please close this issue so that it will disappear from my todo list. Thx

**Comment by Dashkinru** [comment]
I'd like to be happy! It's almost ok. But the colour of the text is blue. For some teachers it might be an issue. Could you change it for black.

**Comment by a34alefeliza** [comment]
done.
