### ISSUE TITLE
add text collection pa.lesson5.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#28]
Hi! I don't know whether Julia told you about that or not but we wanted to ask you to make a board game with text 1 collections. And make the space between the cards narrower in order to fit more cards on the screen. Now it's 7*3 grid. And I'd like 8 * 4 grid.

**Comment by a34alefeliza** [comment]
you can use the brand new "grid" collection here! You can set the grid size as you like, adding lines and elements within each line. Elements will have a fixed position, but still you can set the size. Also you can have different alignments (left, right, center, distant). You can play with it to see the different effects. You can sort lines, and you can sort elements within each line. Let me know how it looks!

**Comment by Dashkinru** [comment]
OMG!!! You are genious))) Oh I've told you that already)))))
I love it! But I need to test it also))
