### ISSUE TITLE
collection with answers

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#29]
It's vitally important to have "something" to type keys for the exercises. Our course will be mainly based on grammar and it will be our strong point. This way we have to think up smth for the teachers to keep their answers for the ex-s. For each separate collection. So that I can do it as admin and other users too in their private collections. I see it as a key column  (like images 1, text, etc). Maybe a user can save this info there and then click on a button in the teacher panel to open these keys for themselves.

**Comment by a34alefeliza** [comment]
I could add Keys (or Notes) when clicking the three dots (Edit/Copy/Notes) and then recall these notes from the toolbar

![image](https://user-images.githubusercontent.com/9462653/102413107-bcf9f500-3ff4-11eb-8e9c-a68d8da6dce7.png)

**Comment by Dashkinru** [comment]
I think it's ok. Why not))) Let's try)
Thanks a lot))

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/103302992-33d7ba80-4a05-11eb-9815-041683d0b6a0.png)
Would this new button replace the Help button? The difference that I see is that help button refers to the exercise, while the new button refers to the collection. Is that right?

**Comment by Dashkinru** [comment]
Yeap! You've hit the nail right on the head!!! This HELP button displays the rule for the exercise itself. And we need a button to open the keys for EACH collection. And creating these keys must be accessible for all teachers.

**Comment by a34alefeliza** [comment]
you have Keys on collections:
![image](https://user-images.githubusercontent.com/9462653/105424893-83965400-5c48-11eb-9211-5c4cc2600636.png)

You can visualize them clicking on the toolbar help button:
![image](https://user-images.githubusercontent.com/9462653/105425043-de2fb000-5c48-11eb-9bfb-426699339c36.png)

IMPORTANT this feature is only available for mixed and grid collections. One by one we need to migrate old collections (img/img2/text/text2) to mixed/grid

**Comment by Dashkinru** [comment]
Hi! I've checked KEYS out. Everything works well. Thanks!
You said that we need to migrate from old collections. How much time does it take? Is it difficult? 
I haven't done anything serious yet on MP. I'm preparing everything only in my drafts and personal collections.

**Comment by a34alefeliza** [comment]
I will migrate collections only when needed. On MP you should only use mixed/grid collections. So if you need a template which is still working with img/img2/text/text2 you tell me and I will migrate it.

BTW when are you planning to start with MP? Do you have a timeline?

**Comment by Dashkinru** [comment]
Do I understand it rightly, that you will change the collection, but the function remains the same? And you will be able to use only a part of mixed collection potential? 
And I DO plan to start with MP but with these collection changes I got confused and had to think the structure over again. Besides I want to look through the issues on GirHub with you today and maybe close some of them because there are too many of them. 
About the timeline... I want to do it as fast as I can. 
The problem is that I need to make videos to show how it works. And if I'm making a video, the exercise should be finished completely so that I am able to show every opportunity to use it. And not to remake the same exercise two weeks late. So, for every presented ex there should be a video. 
Let's see each other today and sum up.

**Comment by a34alefeliza** [comment]
As agreed, I have added KEYS to all kind of collections (not only mixed and grid)

**Comment by Dashkinru** [comment]
I see)) Thanks!
