### ISSUE TITLE
Menu in English

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#30]
Hi! Please, when you are creating a home page on the new domein, don't forget that we need everything in English. I don't know whether I have a translator  or the names like Моя Классная Комната are really written in Russian) That's why I dicided to mention this moment.
I'd like to change a little bit the home page. 
1 variant (that I like more)
Could you make the menu names Levels, My Workplans, My Classroom with capital letters, make them bigger a tiny bit, put them in the middle position in the boxes where they are (not from the left side of each box) and create around them an oval frame the same colour like the word Home next to the Pikimoni logo. Also colour the book-signs before level names this colour. And round out the boarders around the submenus making them blue as well. Though the plus, edit and the buttons close and save (and may be other buttons make gold)
If it's difficult tell me what can be done from what I want))
![image](https://user-images.githubusercontent.com/66912801/102825574-147ed300-43f0-11eb-8017-fa71f214405e.png)

**Comment by a34alefeliza** [comment]
Hi Dasha, it's not difficult and we can do that. You will have the possibility to "localize" labels. Localization will apply to my.pikimoni.net only. But all layout changes, such as centering the text or make text bigger, will apply to all pikimonis. This is because I have one "sourcebase" only, which is distributed to different domains. On each domain you have the possibility to "customize" something, such as labels, feeds, corrections...
So, if the layout changes that you propose are good for pikimoni in general, I will be happy to do it. But we need to keep in mind that each layout change that I do can impact other pikimonis... In this case it's an improvement and I dont see any problem.

**Comment by Dashkinru** [comment]
I got it. Then could you discuss these changes with Yulia and tell me
whether you agree or not))
But I don't understand about localization. What exactly will I be able to
do ONLY on  my.pikimoni.net so that not harm other pikimonis.
С уважением,
Дарья


вт, 22 дек. 2020 г. в 12:08, Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
You will have the possibility to contribute this file on my.pikimoni.net:
https://pikimoni.blob.core.windows.net/cdn/dist/labels_en.js
These labels are used on pikimoni and you can customize values. It will require some work from both sides, as I need to add keys into this file, so that you can specify values.

Regarding layouts: I am pushing Yulia for organizing a monthly meeting among all redactors. I think it's already 5 or 6 of you, all very valuables. The idea is to have a kind of brainstorming where you share with each other ideas, improvements, guidelines, best practice, and all these kind of things. This would be the right place where to share also these proposals. I really think that this kind on meeting (we can call it PikiLabs) will be the factory for great ideas. And one day I will also have someone on my side to help me with technical activities. Right now I am the bottleneck I understand...

**Comment by Dashkinru** [comment]
Shall I work somehow with this link? Put it into storage?
https://pikimoni.blob.core.windows.net/cdn/dist/labels_en.js
Speaking about layouts, I agree. Why not? Though it might be pretty difficult regarding different time zones and working schedules.

**Comment by a34alefeliza** [comment]
It is only one hour per month... I think it worth it finding the time!

Yes you will be working with this file, I will tell you how after moving to my.pikimoni.net

**Comment by Dashkinru** [comment]
Let's see. As I've already said I don't mind any meetings)))
С уважением,
Дарья


чт, 24 дек. 2020 г. в 01:09, Alessandro <notifications@github.com>:

**Comment by Dashkinru** [comment]
![image](https://user-images.githubusercontent.com/66912801/106368117-5fc5c300-6358-11eb-8208-95e020bb1e9a.png)

I've checked that everything is already in English on the menu but this part "Мои уроки", and this part
![image](https://user-images.githubusercontent.com/66912801/106368087-1a08fa80-6358-11eb-87c4-a78e569b5e8e.png)
Something you'll change yourself and something I will be able to when you will do some magic on your side. Right?
And here also
![image](https://user-images.githubusercontent.com/66912801/106368134-82f07280-6358-11eb-9ea1-d6855dcfcd46.png)

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/107130189-63fb5e80-68cb-11eb-97d8-3b1fc9c58e82.png)

**Comment by a34alefeliza** [comment]
Actually, I was thinking that maybe I should use colors from pikimoni logo.... it will be a different kind of blue, but everything will be in tune. I will try it, let's see!

**Comment by Dashkinru** [comment]
I think it's great! 
Thanks!

**Comment by Dashkinru** [comment]
1. Alessandro, could you notify me when I'm be able to change these signs .
![image](https://user-images.githubusercontent.com/66912801/107147541-ae2e1f80-695f-11eb-9aac-1eb37434560d.png)
For example, I'd like to make them bigger and change "My Folder" to "My Course". Or it might be much easier for you to change them yourself))
2. Then, in you printscreen the books are blue. Mine are still black. 
![image](https://user-images.githubusercontent.com/66912801/107147631-1a108800-6960-11eb-9de0-947a12dd54ea.png)
3. Next, could you change the name of the course Do it yourself to Online English Teaching?

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/107150104-6f4a9a80-695c-11eb-8bf2-bb83da26ea04.png)

done. I've changed the blue to be the same as the logo one

**Comment by Dashkinru** [comment]
Thanks!))
I showed the signs from the home page to a native speaker.
It's up to you to correct them or not.
But he said that here it's better to say ...visible **to the other person** on the other side (and on the other side may not be used already).
![image](https://user-images.githubusercontent.com/66912801/107276183-b5d6ec80-6a63-11eb-8f8c-9764047c7ce5.png)
Here you have a AmE **organize**, BrE would be **organise**
And lastly here he suggests to change to plural **audios and videos** (because you may count them and the previous words are in plural also)

**Comment by Dashkinru** [comment]
Alessandro, good evening))
I guess the issues that I want to raise are connected to the menu, so I will proceed here if you don't mind.
1. I beg you to modify one more thing on the dashboard - make the words **My courses/My Workplans/My Classroom** bigger and thicker just a little bit. Because titles are usually looks more appealing when they are more noticable.

2. For My Style we need a guide section both for ILE and MP.

3.1 Information for Prices section (if there are any difficulties of organising it, let's discuss))

14 days of free trial period (Is it possible to do it like unlock button? Not right after the registration. So you can open demo, trial period unlocking the course maybe and then if you want, pay for the next period)
14 days - 690 rub
30 days - 1100 rub
90 - 2900 rub

3.2 And you know, I wanted to make my own cartoons. But it will take some time of course)))  That's why, to work with something now, I took an old cartoon from the Net and redone it as an educational format. I read all about copyright and think that I won't be asked to remove it from my Youtube chanel. Several episods have already been more than a year there. And know I change them even more not to have any question. 
On MP I want to make  a new mini course Teach English With Videos. There I won't upload these cartoons. But I will create exercises for the cartoons. And add some **extra** (marked like this) exercises for some videos from the others youtube chanels that are free. In case they become not free, people will buy them or just won't use them.  As I've said, it will be some extra material.
What do you think?
If you don't have any objections, could you make such a level. 
Price 30 days - 330 rub (without 14 or 90 days)

4. Contacts. What information should be given there? The same as now but to match "the style" in English? But about support email, skype and vk?

5. Today I wasn't able to register on MP. Something wrong there?
I'l like you to add an obligatory telephone box to the regictration info. Ok?))

**Comment by a34alefeliza** [comment]
1. English text fixed.
2. Titles My courses/My Workplans/My Classroom are bigger
3. guide: create a new file called styles.md in _intro/en/dashboard_ folder
4. prices: you can edit this file: _home/ru/prices.md_
5. free trial: you want to start the free trial when unlocking the course, before attending the webinar? Or there will be no webinar at all? I need to check how complex it is... this part is common with ILE
6. course Teach English With Videos added
7. prices updated
8. contacts: until you don't have your own site, it can be your contacts. You can also send me a picture if you wish
9. registration is also common. I will ceck with Yulia about mandatory phone number.
.

**Comment by Dashkinru** [comment]
Hi! Thanks a lot for everything you've already done))
5. There will be no webinar. I'll create a row of videos which will work as guides without any additional active involvement on my side. So, pls, think how to deal with this moment and ILE.
6. Thank for the course Teach English With Videos but shouldn't there be any link in the storage to make it possible to use for me?))
7. Ok. I'll give you info within few days.
8.  Got it about the phone number. Inform me, pls, which decision you will make)

**Comment by a34alefeliza** [comment]
I though you don't need a storage, as you are using youttube video... BTW here it is:

https://pikimoni.blob.core.windows.net/diy-video?sv=2019-12-12&st=2021-01-01T00%3A00%3A00Z&se=2031-01-01T00%3A00%3A00Z&sr=c&sp=racwdxlt&sig=ltqgKHaCgPViuzvwsip7d4kXr06USL0117fP3SfJsDk%3D

**Comment by Dashkinru** [comment]
There will be some gifs and pictures for these videos.

пн, 15 февр. 2021 г., 16:34 Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
registration completed, with phone number (mandatory) and in english.
I have also removed the FREE/FULL PLAN boxes from the homepage since there will be no webinar.
I will put your contacts and the presentation video of your course once you provide it to me.
