### ISSUE TITLE
style and colors

### ISSUE THREAD

**Issue by a34alefeliza** [a34alefeliza/ile-pikimoni#32]
on the toolbar you can click the button to change style and make cards more bright:

![image](https://user-images.githubusercontent.com/9462653/103180937-5948b500-489b-11eb-9f64-0f4d44a9ff41.png)

At the moment it only works for MATCH exercise on https://my.pikimoni.net

**cards**: allow you to change color and style for cards

**text**: you can overwrite the font from the text collection with a different font. I will add opendyslexic here. You can even disable the text color and work with black&white only

**general**: this is for page background color. I will add wallpapers images here

_NOTE_ at the moment this is a general setting. It means when you change the style it will apply to all pages. Yulia suggests that styles should be page-specific: each page its own style. What do you think?

**Comment by a34alefeliza** [comment]
there is a new section "My styles" on the teacher's menu where you can set global styles:
![image](https://user-images.githubusercontent.com/9462653/103454845-20b83980-4ce8-11eb-8991-cca76219dcfa.png)

These styles will apply everywhere on pikimoni. For example the wallpaper, or the text fonts.

But, you can overwrite global settings on a specific exercise, using the _style_ button on the toolbar:
![image](https://user-images.githubusercontent.com/9462653/103454887-7a206880-4ce8-11eb-8001-92736d225796.png)

In this case you can style will apply to this exercise only.

How does it look?

**Comment by Dashkinru** [comment]
I think everything looks wonderful))))
I managed to set a wallpaper. But failed with changing the style of separate exercises and creating boarders . Maybe because you haven't just finished with it yet))

**Comment by a34alefeliza** [comment]
which exercise?

**Comment by Dashkinru** [comment]
Now it seems to me that  CHANGE STYLE  works everywhere where it is possible. You made this button inactive in some exersices, if it's not possible to use, right?! 
In this exercise (pa.sort-numbers.html) I can't create boardes though I thought I would be able to. Can you  change this?
