### ISSUE TITLE
make transparent pa.findWord.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#38]
Could you make this greyish area around the possible images transparent in this ex pa.findWord.html?
![image](https://user-images.githubusercontent.com/66912801/105029865-f7c3d280-5a63-11eb-9176-b930fc461a0e.png)
And pls, confirm my guess. It's NOT possible to highlight a peice of text in this ex (even if I ask you to change this) like in a usual text here
![image](https://user-images.githubusercontent.com/66912801/105031448-60ac4a00-5a66-11eb-8ee3-e515eab6c052.png)
You know why I'm asking?! Because when you work with a text and ask to read this or that piece, it's convenient to highlight THIS exact piece. And of course we can open the execise like this and have no problem. But there is one BUT... there are no pictures can be shown at the same time. In our exercise pa.findWord.html, that we have here, teachers can display and images and texts, but they can't highlight a piece of text.
How could we solve this "problem" in a way that is easier for  you?

**Comment by a34alefeliza** [comment]
done, both transparency and text selection.

**Comment by a34alefeliza** [comment]
done
