### ISSUE TITLE
! Questions about grid collections

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#39]
![image](https://user-images.githubusercontent.com/66912801/106439443-c0ecb400-6488-11eb-8518-d68166769b7f.png)
Here works everything but videos and cards.
1. Videos you'll fix as I understood.
2. Cards work with text now. Will they work with the rest suggested buttons? 
![image](https://user-images.githubusercontent.com/66912801/106440015-66a02300-6489-11eb-9108-a6007e9b3b96.png)

**Comment by a34alefeliza** [comment]
yes video will work. 

Regarding cards: I will fix images, and I think I will remove audio for the time being. In short, only image, text and url will be available.

**Comment by a34alefeliza** [comment]
can you check now, it should work. You can add image, text, url and audio to cards. But I will work a bit more on audios as they are not yet working as expected.

Also you can add video to mixed/grid collection. Give it a try and give a feedback!

**Comment by Dashkinru** [comment]
A card in a grid works well!!!
About video... It works. But it is everywhere so small...
![image](https://user-images.githubusercontent.com/66912801/107150063-00c20880-696d-11eb-88d4-7b82c61664d9.png)
Maybe we need a specific template too make it bigger?

**Comment by a34alefeliza** [comment]
:-) I will work a bit more on it...
