### ISSUE TITLE
Make text2 coloured pa.selectWord.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#4]
Could you make an exercise like this one but with a drop down menu instead of text boxes pa.findWord.html
The idea is to make the process of giving answers faster. Sure they can just say them, but it's nessessary to interact and keep students focused.

**Comment by a34alefeliza** [comment]
What do you mean by drop down? This is what we have now:
![image](https://user-images.githubusercontent.com/9462653/99915253-e6c84080-2d02-11eb-9476-6b7bc7464fbc.png)
How should I display text?

**Comment by Dashkinru** [comment]
Alessandro, I don't inderstand...The templateUrl is copied rightly but that's not what I see in your message, not this exercise. I mean this one
![Снимок экрана (52)](https://user-images.githubusercontent.com/66912801/99989545-c9a77680-2dc3-11eb-8a42-2c089bf3895b.png)

**Comment by a34alefeliza** [comment]
ok so instead of ****** there will be a dropdown menu with possible answers, and the student needs to select one. We need a new collection text2 in order to provide dropdown options. Is my understanding right?

**Comment by a34alefeliza** [comment]
Is this what you need?

![image](https://user-images.githubusercontent.com/9462653/100374499-b0453b00-300c-11eb-95d8-56f3ab728407.png)

**Comment by Dashkinru** [comment]
You are absolutely right)))
С уважением,
Дарья


чт, 26 нояб. 2020 г. в 19:28, Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
Done. I have created for you an exercise called "dropdown CHANGEME" on diy.

**Comment by Dashkinru** [comment]
I will try it today)) Thank you!
С уважением,
Дарья


вс, 29 нояб. 2020 г. в 00:34, Alessandro <notifications@github.com>:

**Comment by Dashkinru** [comment]
I am sorry(( I can't figure out how to create text 2 rightly(( 
With comma? No. With hashtag? No. With the next line underneath? NO! Then how?)

**Comment by a34alefeliza** [comment]
just with space! But yes, need to find a way to make it more clear... or better to use hash?

**Comment by Dashkinru** [comment]
hash will work good. Because teachers may need phrases

**Comment by Dashkinru** [comment]
is it possible to create horizontal and vertical positions for images1 here? I ask about the same for this exercise as well pa.findWord.html 
Maybe you've already thought about it?!))

**Comment by a34alefeliza** [comment]
ok, done with hash. About vertical/horizontal positioning I need to think... I think we have another issue about it to track the progress. I will update you there.

**Comment by Dashkinru** [comment]
Thank you!))
You know it's not possible to colour text 2. Ok! I can colour while editing, but **the words are not colored** when the exercise open.
