### ISSUE TITLE
! Questions about mixed collections

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#40]
1. Is it possible to make the paragraphs in text collectoins?
![image](https://user-images.githubusercontent.com/66912801/106440436-e9c17900-6489-11eb-93c9-739242444853.png)
2. Can I make the windows with images smaller or bigger? 
3. Can you add a pointer function here and a possibility to hightlight the text?

**Comment by a34alefeliza** [comment]
Hi, the question is wrong ))

Collections represent some plain content: text, images, audio. How these contents are displayed on the page and how to interact with them, it's up to the template that you are using. So if you need paragraphs, the ability to select text or to size images, you need to pick-up the right template.

Is there any template already doing what you need? If so, what I can do is to make it work with mixed collections (probably at the moment it only works with text collections). So you can tell me the name of the template that you want to use and I will do the rest.

**Comment by Dashkinru** [comment]
Ok! Thanks! I thought like this too but I also was wondering whether I
could use the mixed and grid collections without the specific template and
to what extent they are flexible.
Now I see it))
Yeah. Then I will text you today what and where we need to substitute with
new collections.

пн, 1 февр. 2021 г., 18:32 Alessandro <notifications@github.com>:
