### ISSUE TITLE
I have a problem with stickers

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#41]
I can't create an admin collection in stickers.
https://www.loom.com/share/e01a6e6abd6b4a72a342301398b2fe5b

**Comment by a34alefeliza** [comment]
fixed! Regarding labels, refresh the page (ctrl+R) and they should appear....

**Comment by Dashkinru** [comment]
![image](https://user-images.githubusercontent.com/66912801/107156206-13990500-698e-11eb-827d-6b5054ed9546.png)
The tick is still vanishing. Though I managed to create an admin collection.

**Comment by a34alefeliza** [comment]
it should be ok now. I had to remove existing sticker collections, sorry about that...

**Comment by Dashkinru** [comment]
Thanks!!!
С уважением,
Дарья


чт, 11 февр. 2021 г. в 00:54, Alessandro <notifications@github.com>:
