### ISSUE TITLE
Guide: My Style

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#43]
The guide keeps missing My Style section. Shall I do some actions to activate it?

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/107942432-822c2300-6f8b-11eb-853b-083639a756ed.png)

Yes, a new entry needs to be added into the Guide. If someone has already completed the guide, it will only get the updates. This is why it is important to set the date on new entries (as you can see, the #f-styles entry has got today's date). The system is checking what each user has seen last, and will only display the new entries.

I hope it's clear... :-)

Remember that the guide can span into multiple pages. So if you want you can document the toolbar, or anything else. If needed, I will explain you how to do that.

**Comment by Dashkinru** [comment]
)))) While I was answering that didn't understand anything about dates and entries, it dawned on me!)) Now I know what you were saying))
About the toolbar I understood as well. Will think about it.
