### ISSUE TITLE
Deleting of unnecessary exercises

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#44]
I asked you recently on What's App about the possibility of deleting the exercises which I don't need now because you were able to change so much on MP for the better))) You haven't answered yet. So I decided to open the issue here in case you forgot))
It's important because I will remove all the unnecessary ex-s and I will ask you to substitute the remaining ones with mixed and grid collections.

**Comment by a34alefeliza** [comment]
Done, now you can remove exercises. This possibility will be there while the course is not active. Once the course will be activated, the REMOVE button will no longer be available, as teachers may have added any exercise to their workplans.

**Comment by Dashkinru** [comment]
Thank you. Got it!
