### ISSUE TITLE
Match - correct a little bit pa.match.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#45]
![image](https://user-images.githubusercontent.com/66912801/107861498-337d6c80-6e57-11eb-91d9-b3c694200a6c.png)
When we were having a call on Skype, you told me that it is possible to 
1. fit in all the cards from mixed collection in the screen so that they won't go beyond the screen boarders;
2. make the gaps between the cards maximum smaller to give more space for cards themselves

3. Today I saw that the boarders around the text collection vanished...
4. But maybe it's not even important because I ask you to change the text and image collections here  for mixed ones ( if I understood you rightly, you wanted to do it.)

5. And alsо could you add more space between the top row of card and the bottom one?

**Comment by Dashkinru** [comment]
Alessandro, hi! 
1. I'm still asking you to fix the cards inside the screen boarders no matter how many of them there are. Is it possible?
![image](https://user-images.githubusercontent.com/66912801/133137351-5fed3f4c-a9b1-4159-a0d0-e036270de05d.png)
2. The cards are out of card borders from one side. If it possible to fix it?

**Comment by a34alefeliza** [comment]
1, you can play with size... I am not able to fit images inside the page automatically, you need to do it manually. Or you mean that images should wrap on a new line?
2. fixed

**Comment by Dashkinru** [comment]
If it's impossible to fit all images inside the page automatically, then the work on this exercise is finished. Thanks!
