### ISSUE TITLE
Add new exercise

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#46]
Hi! I have some questions. 

1. I wanted to add a new ex on MP but saw that I can choose only from the tamplates which are already on MP. I need to add a tamplate from Clumsy level (pa.write-word.html). I shall ask YOU to do it, right?

2. We don't need collection Cards any more, do we? Because now we may use grid. 

4. On the whole everything that now is under the name BEGINNER and separate games underneath I would ask you to substitute with mixed or grid collections.

**Comment by a34alefeliza** [comment]
1. done, you have a new button to create new ex
2. right, we dont need it
3. sure. Can you tell me the template's name?

**Comment by Dashkinru** [comment]
1. pa.text-sentence.html - do we need to change anything with text collections?!
2. pa.text.html
3. pa.selectWord.html
4. pa.findWord.html
5. pa.sort-numbers.html
6. pa.sort-rows.html
7. pa.guess-word.html
8. pa.flip3.html (with cards we are able to create front cover for every card at the same time. Will it be possible to do the same for the grid collection?)
9. pa.office.html
10. pa.jcrop.html (I am not sure about this one. On the one hand I don't need it. But it allows to make pictures really big. With grid or mixed collections I can't make the pictures as big as I want. Maybe because it requires this specific tamplet of pa.jcrop.html? Here you can see what I mean.) 
![image](https://user-images.githubusercontent.com/66912801/111042478-aa098c00-844e-11eb-9ff9-7804c6a8e36c.png)


![image](https://user-images.githubusercontent.com/66912801/111042492-b5f54e00-844e-11eb-8be9-9de6b8f3cc13.png)

**Comment by Dashkinru** [comment]
Hi! Could you have a look at questions 8 and 10 above? My planning depends on them.

**Comment by a34alefeliza** [comment]
8. Yes we can do that. I will convert pa.flip3 template to use grid collection
10. I don't understand the question... If your purpose is to show one big image on screen, then use jcrop template. With jcrop you can also select a partof the image and play with opacity. Or do you have other needs?
