### ISSUE TITLE
Priority № 1 Homework tab

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#5]
Could you make a tab among "Stickers", "Likes", "Post", etc ( I think it's the best way though I'm not sure))) where teachers would be able to type homework, insert links, and , it'd be just great, save the exercices from the lesson. If, for example, they don't have time to cover some material they'd add it (like with comments) for students' homework page and their students can see it and do in their copybooks. Moreover if the students were able to do these tasks on Pikimoni, it'd be superb!
And one more important thing. It's nessessary for the adminictrator of the course to create a piece of homework as a part of TB. I mean the teacher comes on the Homework Page and chooses a needed piece of homework from the administrator's list/TB list.

**Comment by a34alefeliza** [comment]
This requires time. I will try to do it in the first quarter next year.

**Comment by Dashkinru** [comment]
I completely understand how big the job on this request is. Of course I'll
wait as long as needed.
If you don't mind I'll type you everything that I think is appropriate to
develop the platform and you will already decide what to do with it.
Thanks))
С уважением,
Дарья


чт, 26 нояб. 2020 г. в 00:19, Alessandro <notifications@github.com>:

**Comment by a34alefeliza** [comment]
ok some good news here: I started working to homework. There is a new button on the toolbar, from **Teacher's Book** only:
![image](https://user-images.githubusercontent.com/9462653/103465989-03638980-4d41-11eb-8e09-092c1491f5f3.png)

This button allows you to add a task to a student's homework. You have to select the student on the popup and you will see all tasks currently assigned to him:
![image](https://user-images.githubusercontent.com/9462653/103466012-47ef2500-4d41-11eb-86db-40ace306d8f9.png)

Then, the student will see on his homepage a new tab called **Homeworks**:
![image](https://user-images.githubusercontent.com/9462653/103466030-7b31b400-4d41-11eb-8822-ea6a75722997.png)

Clicking the start button he will enter the page and start the homework. Once done, he needs to click the _done_ button:
![image](https://user-images.githubusercontent.com/9462653/103466053-b633e780-4d41-11eb-9304-d150d3de16cc.png)

The teacher can check the homeworks selecting the student:
![image](https://user-images.githubusercontent.com/9462653/103466101-fc894680-4d41-11eb-9036-a30b231c6402.png)

and will be able to approve (ok) or re-assign the task to the student (re-open) if needed:
![image](https://user-images.githubusercontent.com/9462653/103466127-41ad7880-4d42-11eb-85b5-d72f4bcf39f7.png)

You can check the first draft here:
https://dev.pikimoni.net/home.html#!/pa/dashboard

**Comment by Dashkinru** [comment]
WOW! What else can I say?!)))
You did it!!! I tried it. Seems to me everything works))
1. Later will it be possible to give the hw not only through Teacher's Book? Because this way teachers will create their hw collections.
2. Is it possible not to choose a student in My Classroom to assign them hw?

**Comment by Dashkinru** [comment]
Could make this sharing-thing only on the student's page? Not for every user to see? Maybe we to make an option - share on a WALL/share to students page. 
![image](https://user-images.githubusercontent.com/66912801/103944919-6b511000-5145-11eb-9378-c09608be5a46.png)

**Comment by Dashkinru** [comment]
After our discussion I leave these two questions to work on (from the old message)
1. Later will it be possible to give the hw not only through Teacher's Book? Because this way teachers will create their hw collections.
2. Is it possible not to choose a student in My Classroom to assign them hw?
3. And I ask you to create a possibility to leave comments somewhere, so a teacher can say what exectly was wrong or why they want a student to redo their hw.
4. Also there should be some place where a teacher could just insert a text exersice or a link for the student. Maybe it is again will be in the comment section. 
5. I would like to create admin homework. For example I create a lesson in the TB and then somewhere the HW for this lesson in the TB. Teachers will be able to to click somewhere and assign this HW to a student (but change it if it's necessary)

**Comment by a34alefeliza** [comment]
![image](https://user-images.githubusercontent.com/9462653/108627882-0719af80-7458-11eb-8deb-f9175de9ec6d.png)

this is when publishing posts (public or private)

**Comment by a34alefeliza** [comment]
1. I can add the possibility to assign home works from Workplans. This way teacher can create his own collections, add them to the a workplan, and assign homeworks from there.
2. you mean choosing the student from the popup after clicking on the toolbar button? Yes, it should be possible
3. done, check please
4. done, you can click the _plus_ button on the student's page and add a new task. You need to provide a test description.
5. I am not sure. You can already create system collections and add them to TB. From there you can assign homeworks. It should be enough...

**Comment by Dashkinru** [comment]
Hi! Sorry for not answering so long - my children were at home ill last week and didn't give me time to work on Pikimoni.
I would like to clarify something. Do you have any negative feelings about me putting off the start of the platform? I understood that there was more preparation work than I though it would be. And some outer factors do not allow me to move as fast as I want. I feel miserable about it. And I promised you to start around New Year. I usually do what I say. That is why I feel even more frustrated.
About sharing - thanks, man))) It's cool!
About hw. 
1. Please, change the tab name to Homework (without s - 'cos it's uncountable)
2. Please, add this oppotunity to add hw via Workplan. And a question here. Maybe there's a possibility to add hw rigth from the collection???
3. I tried to leave a comment and it works well! Though I tried to add an exercise from the TB and couldn't. Is there a mistake on my side or you didn't finish it?

**Comment by a34alefeliza** [comment]
No problem regarding the go-live of your level. Take the time that you need. :-) 

Two notes from my side: 

1. pikimoni is a work-in-progress. As you know it is always changing with new features and new ideas. Sometimes it happens that with new features appear also new bugs, that I try to fix as soon as possible. I have in my road-map to implement automated tests to reduce these kind of incidents. But I dont know when I will do it...
2. I will enable homeworks on ILE only from September 2021. And it will be a _premium_ feature. The idea is that students will have two options: the _basic_ subscription which is free, or a _premium_ subscription which will have a cost. We did not fix the price yet, but il will be not expansive. All existing features will stay free. The premium subscription will include Homework and new features such as Friends and Stories (Friends: possibility to connect with other students like in a social network. Stories: possibility to use stickers to buy stuff and complete a story). For MP everything will stay for free for students, at least at the beginning. We will see in future.

**Comment by Dashkinru** [comment]
Hi! Is it possible to launch the simplest version of homework for MP in the nearest future? PLEASE!!! I'll do whatever you want :) :) :)

**Comment by a34alefeliza** [comment]
Hi! You already have homework in MP... or? Is there anything not working? I am able to add tasks to homework, and I see homework if I login as a student...
![image](https://user-images.githubusercontent.com/9462653/111896286-c8f0bb00-8a18-11eb-98c7-4b4a92a76307.png)

**Comment by Dashkinru** [comment]
Yeah, I can see the homework, as a student, as well. But when I click on
the arrow it doesn't work - nothing opens.
And! I can add exercise only from TB, but I won't form TB in the nearest
future, at least until September. So I beg you to make it possible to add
HW without TB, PLEASE.

вс, 21 мар. 2021 г., 09:41 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
ok the arrow now works.

You can add HW from workplans as well. First you need to add to workplan, and then from the workplan you can add to HW.
