### ISSUE TITLE
Make paragraphes in this template 	/templates/pa.text-sentence

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#51]
Hi! Long time no see :) Don't think I haven't been doing anything :) While you were busy (as far as I know), I was writing and editing texts for instruction videos and promo, creating content and just thinking things over :) Summer's here. I have more time to work on the platform.
Now I am asking for your time again. There 4 priorities. I need to know when you will finish with them and then other issues. It will influence the promo video and the time when the instruction videos will be made. 
Today I have one more question.

Could you make it this way so that the text will be possible to divide into lines (paragraphes)?
![image](https://user-images.githubusercontent.com/66912801/119794039-d37b7500-bedf-11eb-8fee-130128943940.png)

**Comment by Dashkinru** [comment]
and please make paragraph division in this template as well.
**pa.write-word done**

**Comment by Dashkinru** [comment]
Hi! Continuing this topic... I understood that to make a new paragraph or separate questions into different lines I have to add a new line. It's a bit time-consuming. Is it possible to change it or it will be always this way? I'm asking to understand my plan of action :)

**Comment by a34alefeliza** [comment]
what I can do is the following: you enter the whole text in the texarea, and I will automatically split the text into lines and cells. I will use the newline (enter) char to split lines, and the hash (#) char to split cells.

example:

a#b#c
d#e#f

I will split the above text into two lines, and each line will have three cells:
|a|b|c|
|-|-|-|
|d|e|f|

**Comment by a34alefeliza** [comment]
here you go

![image](https://user-images.githubusercontent.com/9462653/130322180-73c287b5-7e35-43e4-8f2b-8cbdbab8d684.png)

**Comment by Dashkinru** [comment]
Thank you!
