### ISSUE TITLE
Can't remove an admin collection

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#52]
Hi! I wanted to delete a collection in exercise Drop Down. But it's said that it's used by 4 workplans. I don't have any workplans. What should I do?
![image](https://user-images.githubusercontent.com/66912801/120121203-c80f9e80-c1aa-11eb-915e-bec4cd5b3fbd.png)

**Comment by a34alefeliza** [comment]
maybe someone else has put this collection into his workplan, and this is why you can't delete it.

Need to analyze this case and find a solution...

**Comment by a34alefeliza** [comment]
problem here is that collection might be used in teacher's book or in workplans.

If it is being used on teacher's book it can not be deleted. You will need to remove it from teacher's book first.

If it is being used on workplans, you can only deprecate the collection. It means that it will no longer be visible anywhere except that in those workplans where they are still referenced.

If it is not being used on teacher's book nor in workplans, it is physically deleted from pikimoni.
