### ISSUE TITLE
The tick disappears

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#53]
I created 2 new exercises. But I think I did something wrong because when I put a tick to choose a collection in exercise Text Box + Image and Text Box 2.2, it doesn't open anything (the page is blank) and the tick disappears when I am back to the collection choosing page.
![image](https://user-images.githubusercontent.com/66912801/120121375-c692a600-c1ab-11eb-8c16-db4d71910a1a.png)

BTW, while we are on this topic. I badly need this type of exersice (/templates/pa.look.html?d05bdf93ab933cba) but not with this opption (may I not explain why? 'cos it's long:)
![image](https://user-images.githubusercontent.com/66912801/120121419-fd68bc00-c1ab-11eb-8442-96e96fc8f30d.png)
but with pointer function. Is it diffiult to create this type of template? 
![image](https://user-images.githubusercontent.com/66912801/120121457-3f91fd80-c1ac-11eb-8989-73cc87dd906b.png)

**Comment by a34alefeliza** [comment]
1. which exercise is having the problem? How can I find it and check it?
2. would be ok to add the pointer to the icons in pa.look.html template?

**Comment by Dashkinru** [comment]
1. I didn't copy these exercises. I've added them. I think, if both are not working, I did it in a wrong way. The exercises are Text Box 2.2 and Text Box + Image on MP.
![image](https://user-images.githubusercontent.com/66912801/120888408-db829580-c600-11eb-97eb-c0064fffb680.png)
2. You know, because these markers 
![image](https://user-images.githubusercontent.com/66912801/120888507-4e8c0c00-c601-11eb-969b-4becb026de2d.png)
 still are working incorrectly with some students (you click in one place, the student sees it in another, and it causes some trouble) I think it's better to avoid unnecessary discussions and complaints from users and do not use  these markers at all. Plus it's imposible to delete them and it also brings up some inconvenience. 
That's why it would be much better to create a template where we can use only a pointer. Although, of course, if it's too troublesome, I agree on everything you suggest :)

**Comment by a34alefeliza** [comment]
1. fixed
2. if this exercise doesn't work well then I need to fix it. Creating a new exercise would only spread the same problem around. What are the issues?
    * click on one place and student see it on another place
    * delete placeholder
    * anything else?

**Comment by Dashkinru** [comment]
1. Thanks!
2. Let's before this try something esle. Maybe I won't need this template at all if you change an old text collection to a mixed one here  **pa.text-sentence** and here  **pa.write-word**. If I imagine it correctly, it would be possible to use these exercises not only with texts, but with pictures as well. The only thing that is needed a pointer in both and a paragraph devision in the first one (pa.text-sentence).

**Comment by a34alefeliza** [comment]
pa.write-word done.
pa.text-sentence is more complex, I'll try later.

**Comment by Dashkinru** [comment]
**pa.write-word** works exeptionally well! Thanks! The only thing here is needed to be done (if possible) paragraph devision as well as in **pa.text-sentence**.

**Comment by Dashkinru** [comment]
I will close this issue and open a new one with the last messages from here.
