### ISSUE TITLE
I can open and deal with these exercises in admin account but can't in common user's one.

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#56]
These exercises are 
**Fill in** /templates/pa.findWord.html?d31d0fb415bb33dd
**Quiz** /templates/pa.new-millionaire.html?a24b4357f97761b9
**ODD ONE OUT** /templates/pa.flip3.html?e5e4460a96f26cdf
**THE BANK** /templates/pa.grid.html?72ca9654f9d8d2ac
**THE RACE** /templates/pa.grid.html?72ca9654f9d8d2ac

**Comment by a34alefeliza** [comment]
Hi Dasha, sorry for keep you waiting, I really have a bad time with my official job. it's ILE or MP? You mean, these templates do not open for teachers and students?

**Comment by Dashkinru** [comment]
Hi! That's ok. No worries.
It's in ILE. Year, a teacher can't open it. I click on the exercise and
NOTHING happens, as if I didn't click at all.


вс, 27 июн. 2021 г., 16:14 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
so strange. Which exercise is not working? I can open "Text With Images"

![image](https://user-images.githubusercontent.com/9462653/123547394-e395a700-d760-11eb-8016-51f8e5bd85c4.png)

**Comment by a34alefeliza** [comment]
I think I have found the issue. Please edit and save these exercises using your editor account (icanwrite). You dont need to change anything, just click the save button to fix the issue.

**Comment by Dashkinru** [comment]
Everything is working now! You're the legend!
