### ISSUE TITLE
Make "Progress" page for DIY

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#57]
Hi! I was awfully sorry to hear about your broken arm! I hope will get better as soon as possible.

Regarding the work...
We need to make a page My Progress for DIY.
This is a grid with skills which are gonna be checked. The vertical column will contain not units but 12 Progress Check sections.
![image](https://user-images.githubusercontent.com/66912801/127749053-3ca43a22-8438-4aff-81e6-0ddbd033cc15.png)

**Comment by a34alefeliza** [comment]
thank you...

shall I put the heart-icon to mark a unit as done? Or do you want a different icon?

**Comment by Dashkinru** [comment]
Could we use numbers range from 9 (top) to 1 (bottom) and letter U under
number 1?
The example is attached.

вт, 3 авг. 2021 г., 11:46 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
done

**Comment by Dashkinru** [comment]
Thank you! Everything works well!
