### ISSUE TITLE
A bug (I guess)

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#58]
Hi! Alessandro, I've noticed that when using "add URL" option it fails my now and then. On Wednesday I made this collection with 2 url images. Today one image is there (from the Net), the other is not (from my VK private files). I've noticed it not for the first time. But I can't follow the logic. Maybe you have an assumption on this question. Because it  super important. 
![image](https://user-images.githubusercontent.com/66912801/130229512-b06fc4cf-8d84-43a0-af68-74d7f9a54454.png)

**Comment by a34alefeliza** [comment]
I guess the image from vk that you are trying to use is not public. Not all sites allow to embed their images into an external site. I guess this is the case...
yuo can press F12 and check the console. I bet you will find some errors related to CORS.

**Comment by Dashkinru** [comment]
the thing is that it works  at the beginning, but vanish later. And I can't figure out the time period after which it disappears. For example, yesterday I made two collections for the test: one with url from the net and one with VK url. Today they both work perfectly well. I'll take a look at them tomorrow.

**Comment by a34alefeliza** [comment]
I don't know, maybe that image has been removed from vk meantime. what is the exercise/collection?

**Comment by Dashkinru** [comment]
The image was on VK 100%. It's my personal files. I checked them after each
disappearance :)
Why I am worried so much is because it's one if the MOST essential part of
DIY course.

вс, 22 авг. 2021 г., 00:01 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
can you send me the file's url? If it's a personal file I guess that it is only available to you when you are logged on vk, and not to others. Maybe you have to turn it into a public file.

**Comment by Dashkinru** [comment]
My students can see these files on Pikimoni without any problem. As for
making it public, it won't do. They're privet - students' hw, etc
Yeah, my test files have been visible on Pikimoni since Wednesday, both the
Net URL and VK URL. I told you 🙈, I can't understand the pattern, what
triggers VKs to disappear. Though I remember that some Internet URLs
vanished once. But with them it's easy to assume that they were simply
deleted or modified.

Here's the URL for the file I've been using. Once exactly this image vanished. And now , after the second collection creation , it's been there for 5 days.   

https://psv4.userapi.com/c505536/u29078828/docs/d49/f4a1d6f5185d/WhatsApp_Image_2021-08-16_at_14_42_44.jpg?extra=HZW_jdPfQox6QK1fnqQ8L2zo1_ODpDv_pIV0E06MdVZxIZNcRtsIyY_-woddj4bpVElf-v8pTkBX3BAeoVVnZHRRVOATjOJ_SViz14yW45ekKlPVsd5o7lMBWLOsntsS1kp2AlOkxzhItxGVYKg4jWA

![image](https://user-images.githubusercontent.com/66912801/130354492-7f3c54a7-5b89-4aa5-8ecd-44da209324d2.png)


вс, 22 авг. 2021 г., 14:51 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
well I don't know, but I exclude it is a bug on pikimoni. Next time it happens press F12 and check errors on Console and Network tabs...

**Comment by Dashkinru** [comment]
Ok. Everything still works. I'll be monitoring this. Meanwhile, I'll close this issue.
