### ISSUE TITLE
New template (modified pa.selectWord)

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#59]
https://www.loom.com/share/7338783bd6e44ae09654bdec865d6cb5

**Comment by a34alefeliza** [comment]
Sorry Dasha, the video on loom is no longer available, probably it expired after few month... can you describe again the new template please?

**Comment by Dashkinru** [comment]
Sure :) Now I can create only one drop down box for the whole exercise.  So in each gap where you shall choose the answer these answers would be the same.
![image](https://user-images.githubusercontent.com/66912801/182583014-aaa148bb-9d34-4265-892d-006141b27ea2.png)

Can you do it this way so that users  have a choice to add the INDIVIDULA drop down boxes for EACH gap or like it is now - one box for all gaps. 

I mean like this:
1. Can I [have/has] a glass of water? *In this drop down menu there are two verbs HAVE and HAS*
2.  [Open/opens] your book. *In the menu to this sentence there are already other verbs*

**Comment by a34alefeliza** [comment]
ok this is possible but it will take some time. I need to change the grid collection and allow to add a new kind of element representing the combobox. I will try by end of month.

**Comment by Dashkinru** [comment]
I see. OK. Thank you! I will count on this template then.

**Comment by a34alefeliza** [comment]
Hi Dasha,
it took a bit longer than I said, but I have now implemented the feature youe were asking. When editing collections (grid/mixed) you will see a new button: "add options" that you can use to diplay a selection box with options:
 
<img width="447" alt="image" src="https://user-images.githubusercontent.com/9462653/195990311-73c75857-0712-49c7-8a45-450508815c7a.png">

This is how the page looks like:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/9462653/195990378-51abaa21-e88f-4a91-96a2-c411b833f693.png">

let me know if this is enough!

**Comment by Dashkinru** [comment]
Hi! Thank you SO much! I'll check it out a bit later today.

I checked the hw section, though, and now I'm more confused than before.
I'll make a video for today or tomorrow.

сб, 15 окт. 2022 г., 16:57 Alessandro ***@***.***>:

**Comment by Dashkinru** [comment]
> Hi Dasha, it took a bit longer than I said, but I have now implemented the feature youe were asking. When editing collections (grid/mixed) you will see a new button: "add options" that you can use to diplay a selection box with options:
> 
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/9462653/195990311-73c75857-0712-49c7-8a45-450508815c7a.png">
> 
> This is how the page looks like:
> 
> <img alt="image" width="423" src="https://user-images.githubusercontent.com/9462653/195990378-51abaa21-e88f-4a91-96a2-c411b833f693.png">
> 
> let me know if this is enough!

About this new modification. 
1. Can you shift the asterisks a bit lower so that they would be in the same line as the other words in a sentence. 
![image](https://user-images.githubusercontent.com/66912801/196046487-27e5e2a7-f0fe-4903-a08b-ffd8573c9d73.png)

2. It doesn't work in my usual user's account. There is simply  no drop down option. 
![image](https://user-images.githubusercontent.com/66912801/196046570-24aaa4be-ec89-47d2-8f84-bf3b838d7f10.png)

But ! You can see it "inside" the collection.
![image](https://user-images.githubusercontent.com/66912801/196046619-bb2b8713-a7cf-4875-a272-ef1b27c7c8aa.png)

**Comment by a34alefeliza** [comment]
what is your usual user's account? And when it works you are logged with which account?

**Comment by Dashkinru** [comment]
I meant my usual account is my user's account (Dashkinru), not admin.
The option works only on my admin account.

пн, 17 окт. 2022 г., 13:01 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
I logged in as Dashkinru and it worked... can you double check? Can you press F12 and see if there are errors in the console?

<img width="545" alt="image" src="https://user-images.githubusercontent.com/9462653/196533897-d8902fae-6fc5-4f3b-baf7-dc21852600fd.png">

**Comment by Dashkinru** [comment]
Now it works. I don't know what happened before but you saw the screen - the drop down menu wasn't there. 
BTW maybe you have rebooted Pikimoni and that's why everything became OK. This week all my students answers in their homework disappeared. They were very upset. There was much homework. But I calmed them down and said that they didn't have to do it again :) I think this info might be of some importance for you in the future.

P.S.: Will you be able to move the drop down menu a bit lower so that it will suit the whole sentence/line?

**Comment by a34alefeliza** [comment]
Do you remember the eservices that disappeared? I can check...

about text alignment, yes I will do it

**Comment by Dashkinru** [comment]
You know, I have already  deleted all the homework tasks where the text had disappeared. If it happens in the future, I'll let you know immediately.
I guess when you fix the alignment l, you can close this issue.
