### ISSUE TITLE
Need modification pa.findWord

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#60]
Earlier we agreed that an image would be next to the text, not under it. 
1. Could you put it back (next to the text)?
2. Could you add a pointer here, so the teachers will be able to show what they need on this images?
And the same two questions for the template *pa.text-sentence*: shift the image to the right and add pointers.

**Comment by a34alefeliza** [comment]
1. these templates upgraded to grid and they changed a little. Images are no longer to the right column, instead you can have them in one line or you can mix them with text on multiple line. You can put images at the end of each line, this would more or less similar to the previous version.

2. Pointer can be added.

**Comment by Dashkinru** [comment]
1.  I see. But to position the image on the same line as the text, rips the text apart. It doesn't look nice.
![image](https://user-images.githubusercontent.com/66912801/130362682-bd71758c-ac46-40f8-955b-3133816587b8.png)
To out it above the text or under, is the solution. However, I've made cards with grammar rules, and to display them, they have to be pretty large. Otherwise the information is illegible. If I position them above or under, the rest of the text, as you understand, is lost behind the screen.
![image](https://user-images.githubusercontent.com/66912801/130362888-17aea60c-168a-4186-89a0-bc0718d73179.png)
So I see one more chance)) Would you finish this setting (Alignment)? 
![image](https://user-images.githubusercontent.com/66912801/130362976-57f24c12-cf16-402c-8f21-906fd2c53fd5.png)
Maybe with it's help it would be possible to rearrange the image position? Or it won't help?

2. Please, add the pointer. Should I tell you which templates it should be used in?

3. One more theoretical question about this template. We can choose to show or to hide the image. Can you do so that we can do the same with the text. Like we can display both  the text and the image, we can hide everything, we can display the text without the image, and will we be able to display the image without the text? 
![image](https://user-images.githubusercontent.com/66912801/130363269-ba7b784f-5b97-4f3e-a5c5-1fa12d3f563d.png)

**Comment by a34alefeliza** [comment]
ERRATA CORRIGE

for technical reason it is not possible in this case to use pointers. This template uses an _inline_ rendering of the collection resources, which is different from the _block_ rendering that we have elsewhere. I will try to explain the difference by email. In any case, pointers and alignments are not available here, sorry.

I have added thw option to show/hide text. Now you should be fine...

**Comment by Dashkinru** [comment]
I see. Thanks for your time and patience with my ideas and requests.

ср, 25 авг. 2021 г., 23:30 Alessandro ***@***.***>:
