### ISSUE TITLE
Enlarge the gap between the icons

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#62]
HI! 
![image](https://user-images.githubusercontent.com/66912801/130424807-d0777ddd-a17a-4140-b893-4e296ace5779.png)
Could you make more space between these icons, because I've already experienced this problem a couple of times: clicked on the "delete" icon instead of the "editing" pencil? 

Or it might be an option to add a step of confirmation before deleting.

**Comment by a34alefeliza** [comment]
done. Can I close the issue?

**Comment by Dashkinru** [comment]
I've closed it. Thanks!
