### ISSUE TITLE
Remove the tick in pa.findWord

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#63]
I'd like to ask you to do something. I think it won't do anyone any harm if you remove the tick that makes the text visible from the start. The idea is that first the students will see the images (if needed), work with them and then teachers will reveal the text for them. I try super fast to take the tick off when we start the exercises with this template but my students are also fast :) They usually could see and understand what we are going to discuss.
![image](https://user-images.githubusercontent.com/66912801/134802136-52bdfcff-6aa6-4b5d-b2cf-60bd1e88df7c.png)

**Comment by a34alefeliza** [comment]
done

**Comment by Dashkinru** [comment]
Thank you!


пн, 27 сент. 2021 г., 23:34 Alessandro ***@***.***>:
