### ISSUE TITLE
This template is not visible in workplans pa.flip3

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#64]
All exercises with this template ( pa.flip3 ) are not visible in my workplans - the page is blank and when you open the collections the tick is not put anywhere.

**Comment by a34alefeliza** [comment]
can you tell me workplan/exercise please

**Comment by Dashkinru** [comment]
Workplan  Upper Interm 23
Exercise  Off the top of my head (Flipped Cards)

пн, 27 сент. 2021 г., 23:41 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
fixed

**Comment by Dashkinru** [comment]
Thank you!
