### ISSUE TITLE
From one click both a picture and a word are highlighted here pa.findWord

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#65]
Hi! Watch this, pls. 
https://drive.google.com/file/d/19GriEB6_sYBqGzs_xz1YkCriqFm0xcCh/view?usp=sharing

Could you do something so that the images and the words won't be connected. Or, it'd be great if the pictures and the words would be possible to pick out at the same time and they wouldn't be connected: like I can click on the picture I want and the word I want at the same time.
Hope it makes sense)

**Comment by a34alefeliza** [comment]
fixed, now there are not connected. Did not get the second part...

**Comment by Dashkinru** [comment]
Thank you! The second part is not needed anymore - everything is good :)
С уважением,
Дарья


чт, 18 нояб. 2021 г. в 00:00, Alessandro ***@***.***>:
