### ISSUE TITLE
Modify pa.findWord  pa.select

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#66]
I noticed that you've managed to save images on the right side of the screen for pa.select with the help of Collection
![image](https://user-images.githubusercontent.com/66912801/136835190-88f0881f-35a8-40cc-8773-803eaa577e2b.png)
Could you make this type of collection for  pa.findWord?

**Comment by a34alefeliza** [comment]
Hi, done. You need to login as Editor, edit the page settings, enable the new collection:

<img width="436" alt="image" src="https://user-images.githubusercontent.com/9462653/144005957-a0275ebb-c0ca-4e6b-9b28-3f2c4a824ed2.png">

**Comment by Dashkinru** [comment]
:) Thank you SO-O-O much! The last thing to fix is to make it possible to text highlighting. Because I can highlight now only one word at a time.

You know I can't remove the first column with Images. Only you could do that, right? Will you do it then?
![image](https://user-images.githubusercontent.com/66912801/144133890-687af396-8b46-436b-8d60-d1b08a495ca6.png)
