### ISSUE TITLE
Something happened to pa.new-millionaire

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#68]
I don't know why but the image when it comes at the top, changed its position to the left. Could you put it back - to the middle? 'Cause I can't.
![image](https://user-images.githubusercontent.com/66912801/144129449-83ba5f6d-a851-4623-8caf-672e6bf7675b.png)
When a word comes at the top, there's no problem.
![image](https://user-images.githubusercontent.com/66912801/144129573-36800d06-d4d8-4250-8d0b-2972dcb237d3.png)

**Comment by a34alefeliza** [comment]
done
