### ISSUE TITLE
fix text2 pa.findWord.html

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#7]
If it's possible it'd be very handy to have an oppotunity to choose HORISONATAL or VERTICAL image position in this ex. 
Or if it's troblesome than fix images only in horizontal position. That's because they are poorly seen below a long text or aren't seen at all. And the problem is that in those images there grammar hints for SS which they should observe during the ex.

AND could you make images as flip over ones?! In order to focus SS attention on the image that is important at the moment of discission and have all other images "hiden" at the same  time revealing them gradually.

**Comment by a34alefeliza** [comment]
Hi, check what I did: now the position of images is fixed and they will be always visible also in case of long text.

Regarding your second point, what I can do is something like that: I can add an option to choose if you want to show all images at once or one by one. In the second case, only the first image is displayed, and you need to click a button to display the next image. You need to sort images as they will be displayed one by one based on their order. How does it sound?

**Comment by Dashkinru** [comment]
![image](https://user-images.githubusercontent.com/66912801/101279400-15e6b380-37d3-11eb-9cfc-541efd84e8a1.png)
Have a look at the bottom. Due to the image we don't see the end of the text.

As for the second moment I like it . Thanks!!!

**Comment by a34alefeliza** [comment]
I have changed to vertical image position. See if it's better... next, will do the one-by-one image displaying.

**Comment by Dashkinru** [comment]
It's amaizing! Everything works! You are genius))
