### ISSUE TITLE
Homework editing

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#70]
Hi! How are you? 
Here's something that I think we should change. First a bug.
**1.** In the ex-s with this template *pa.match* it happens that when students open their hw for the first time they see everything OK and can do it without any problem.
![image](https://user-images.githubusercontent.com/66912801/178684681-7cff20d3-4b86-4809-90dc-b6327c654a72.png)

But when the teacher opens their hw to check, they see it it a bit lopsided
![image](https://user-images.githubusercontent.com/66912801/178685058-43bb9cc5-8c10-49f5-9e1b-e76d46d60d84.png)

And if the teacher sees some mistakes and wants to resend the hw back to the student, this lopsidedness remains there.
![image](https://user-images.githubusercontent.com/66912801/178685489-364fed04-2624-4399-ab2e-38081e2f34ad.png)

**2.** In the templates (e.g.  *pa.findWord*) where the teacher must tick to display the text or images students cant see anything
![image](https://user-images.githubusercontent.com/66912801/178687771-066d4b16-c97d-4aa6-9736-b35d6318064c.png)

**Comment by a34alefeliza** [comment]
mmh... this is [Match: All at Once] exercise? How did you manage to add it to homework? The button is only present on Teacher's Book but I dont see any teacher's book for DIY

**Comment by Dashkinru** [comment]
One can add anything to homework via workplan.

**Comment by a34alefeliza** [comment]
thank you ))

You know, I'm not able to reprodice the issue. Which collections shall I use?

**Comment by a34alefeliza** [comment]
regarding point 2: once you've added the ex to homework, you need to your student's homepage (from My Students), select his homework, open the ex, click on the checkbox. This event (actually any other event on the page) is registered and when the student will open homework all events will be re-played on the screen. So the click that you did as a teacher (only teacher can see that checkbox) is registered and played each time the e is open.

The same can be done to play the song (point 5 on the issue #71)

**Comment by Dashkinru** [comment]
> reprodice

I didn't get well what you said :) Sorry! :) 
If you mean which collection to choose to try adding it to hw, then it can be DIY "Birds 1". If I understood you wrong, pls pharaphrase yourself.

**Comment by Dashkinru** [comment]
> regarding point 2: once you've added the ex to homework, you need to your student's homepage (from My Students), select his homework, open the ex, click on the checkbox. This event (actually any other event on the page) is registered and when the student will open homework all events will be re-played on the screen. So the click that you did as a teacher (only teacher can see that checkbox) is registered and played each time the e is open.
> 
> The same can be done to play the song (point 5 on the issue #71)

I tried what you've done with the homework - everything works perfectly well. Thank you!!!

Have some problems with adding a song. Text you later.

**Comment by Dashkinru** [comment]
OK. I give up! I can't add a song to the exercise. Please try to do it yourself and if it really works tell me again how to do it. Maybe it'd be more convenient to make a video or have a Skype call for a couple of minutes.

**Comment by a34alefeliza** [comment]
now you have the control panel that you can use to play song (I didn't finish yet)
<img width="742" alt="image" src="https://user-images.githubusercontent.com/9462653/184080259-5f2e99ae-0324-4c38-bcdd-ba0a6b487ff0.png">

**Comment by a34alefeliza** [comment]
there is one more important fact about homework and workplans, it's about collection customization: as you know teachers can customize a collection from teacher's book:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/9462653/184081718-b3984a84-efb3-47f8-b695-843f3c113183.png">
Problem was that the change is "global" and it would apply to workplans/homework/teacher's book at once.

Now you are allowed to make a change on a collection on a specific workplan, and that change would apply to that workplan only. The same for homework and teacher's book.

Customizations are now restricted to a specific scope (workplan/homework/teacher's book) instead of being global. So for example you can have the same exercise on different places, and use different custom collections on each place without impacting each other.

I hope I could explain myself. Let me know if it's clear.

**Comment by Dashkinru** [comment]
I am struggling to understand you and have tried to customize a collection today)) The changes were saved both in a TB and in a workplan: they were global. So correct me if I'm wrong.
1. Now you can customize everything, including the TB. Yes?
2. NOW when you customize one collection in a workplan, this collection will be customized in a TB as well. Yes?
3. You ONLY WANT to change global customization and make it restricted down to 1 collection either in a TB or a workplan or hw. You haven't done it yet. Yes?

**Comment by a34alefeliza** [comment]
I tried to explain with a loom recording. Hope it's more clear:
https://www.loom.com/share/033a94f9283f476e90d50387d504d932

**Comment by Dashkinru** [comment]
Now it's clear! Thank you for this video :)

Let's summarize this issue. Because we have gone astray a bit. Will you deal with point 1 from the first message? After you've done close the issue yourself pls

**Comment by a34alefeliza** [comment]
try now

**Comment by Dashkinru** [comment]
Hi! I have tried to deal with the first point of this issue. Now when you check students' hw, the words are under the images. It's OK with it. Although the images still become very seperated from each other. 

![image](https://user-images.githubusercontent.com/66912801/185048867-cb26576a-5c7f-4c25-8404-6bc1401809d0.png)

Let's agree on that: if it's laborious to put these images together like they initially are, then leave this issue and close it; if you have an idea how to fix it more or less easily, then do it pls.  

![image](https://user-images.githubusercontent.com/66912801/185049661-819e6e18-7f65-4bc3-8e0f-19f6538256c9.png)

**Comment by a34alefeliza** [comment]
it should be ok now, please check and eventually close the issue

**Comment by Dashkinru** [comment]
Hi! Thanks for your work and time. The exercise goes like clockwork :)
