### ISSUE TITLE
Homework ideas

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#71]
**1.** It'd be more convenient to choose all group at once to add homework to theit pages rather than one student after another (especially   from the big group). Besides we should keep in mind that usually there is more than one task to add to all these students.
![image](https://user-images.githubusercontent.com/66912801/180788308-0ba80919-9b06-4c13-a253-58229f2ce2ed.png)

**2.** When the kids have to open their homework and click on the arrow nearby, they always click at the grey button OPEN. And especially at the beginning they won't get it that they must click on they ARROW , not "open". So I guess we will hear about this small inconvenience from other teachers sooner or later. If you could , it's be great to make the OPEN button clickable. 
![image](https://user-images.githubusercontent.com/66912801/180797313-005d71ac-39fc-43ef-971c-16cbe41f1519.png)

**3.** If I were you, I'd highlight somehow the comments section at the bottom of the page. Because if the task is big, kids may not even see that there are some comments from the teacher below the exercise. Or may be it's better to put this text box at the top near the DONE button. This way the students will never miss a word from the teacher. And again I'd make the frame not grey but another colour (red or blue).  
![image](https://user-images.githubusercontent.com/66912801/180800600-bfe8418c-3ef4-499e-8892-587de7812608.png)

**4.** Sometimes the execises we give to the students are quite big and informative. Of course it's possible to open the completed hw first, then go the original exercise where you can see the keys to it, maybe copy the keys and paste them somewhere, so you can go back to the students' homework exercise and compare the answers. I'm sure there lots of ingenious ways to check the kids hw somehow but if we are talking here about  big groups and the convenienc of using the homework option, I think it'd be just wonderful to add (I don't know how if possible at all :) ) the keys section to the homework page. So when a teacher opens the ex to check, they can click on the keys section and see the answers.  
![image](https://user-images.githubusercontent.com/66912801/180804014-a125e16a-b6a7-4ff4-a78e-e89ed22ed0bc.png)

**5.** There's an exercise where kids have to put in order some song lines. Is it possible to add an audio treck to the homework?!

**6.** If a teacher have checked homework and clicked OK, then it disappears, right? But I reckon it'd be better to leave the checked hw and delete it only with the cross/delete button. May be you will want your student to repeat it later or do smth with it later. 

And that basically all there is to it, I think :)

**Comment by a34alefeliza** [comment]
1. now you can select all students in one go: 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/9462653/183151155-5b80f1e9-58bf-45cb-9417-d8ba5d66002e.png">

2. done, now you can click the Open button

3. added Comments button that student can click to read comments 
<img width="137" alt="image" src="https://user-images.githubusercontent.com/9462653/183151478-479e8e0e-f3f4-46e0-a503-c9d9c96eecac.png">

4. I will try to display the entire toolbar

5. you need to open your student's homework and from the toolbar select the song and click the play button. This event is registered and played back each time you or your student open the hw

6. now you have Ok, Re-Open and Archive buttons. Archive button will hide the hw, while Ok and Re-open will only change the status

**Comment by Dashkinru** [comment]
Thanks for your great job! I'm closing the issue.
