### ISSUE TITLE
Change the place of the button "New Workplan"

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#73]
Hi! I'd like to put in my two pennyworth to the alterations in workplans.

**1.** I suggest shifting the "New Workplan" button and "Close" above the workplans' list (because it's inconvenient to scroll down through a numerous workplans to make a new one) and make the first letter in "Workplan" capital as it's a name of a button.
**2.** It'd be wonderful if the new plan became visible after the creation on the Home Page at once. It's just that all these actions take time and make the creation process more complicated: 
1) go to "Manage Workplans" (I suggest to make "Workplans" with the capital letter here as well
2) scroll everything down 
3) name one
4) find it in the filter box or scroll for it
5) mark the star nearby
6) click "Home" or "Close"

Personally, I'd return the "pencil" to alter a plan where it used to be, near the arrow to open a workplan. Let it be two places where you can change something in the plan.

**3.** When you add a plan, it's always at the end of this list (in the screen shot). If the list is long it really troublesome to add exercises to the last plan because of the scrolling. Maybe it'd bу more convenient for users to have only THOSE plans in this list which are active (with marked stars)?!
![image](https://user-images.githubusercontent.com/66912801/204528996-afd819b8-2820-4d73-ac0d-30bb308c449f.png)

**Comment by a34alefeliza** [comment]
Hi, thank you for your suggestions. I implemented almost everything, expect putting the pencil icon back to the main page. I think this should stay on the management page.
When creating a new workplan you can put the star right there.

**Comment by Dashkinru** [comment]
Thank you!!!
