### ISSUE TITLE
HOMEWORK: questions 2. songs

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#76]
Foreseeing the question from our users "Is it possible to add an audio to the exercise?", for example when giving the exercise "Sort out the song lines" (pa.sort-rows), I tested this myself one more time with the screen recording option. I failed with this. 
So, shall I tell in the post that a song/audio isn't possible to add? Or you'll have a look at it one more time?

**Comment by a34alefeliza** [comment]
I would discourage to use songs on HW for the time being. Use the recording-mode actually works but has a lot of side effects: what if the teacher plays by mistake the wrong track while recording? There is no way to remediate other than removing (archiving) the homework and create a new one starting from scratch. Also maybe the student wants to listen the song again, but he cannot. The only option is to close the HW and open it again.

We definetly need a better solution than recording the action. But it will take some time to analyse and implement a proper solution. So my suggestion is: try to discourage adding to HW exercises requiring a song. This will be possible only a bit further in time.

Do you think you will be able to make the post by the end of this month?

Thank you

**Comment by Dashkinru** [comment]
Hi! I got it.
I will do my best to make the post this week.


вс, 11 дек. 2022 г., 18:17 Alessandro ***@***.***>:
