### ISSUE TITLE
3 questions

### ISSUE THREAD

**Issue by Dashkinru** [a34alefeliza/ile-pikimoni#78]
Hi! I've made a video for you. It's easier to explain what I have in mind this way:)
1. Is it possible to use URL images in collection 2 pa.office?
2. Can you make a button to remove all selected collections in one click?
3. Is it possible to highlight or make a frame around the images in pa.findWord?

https://www.loom.com/share/59519fda03824f3788317ff046ba5d86

**Comment by a34alefeliza** [comment]
Hi Dasha,
1. yes it is possible, will do it
2. ok understand the need. I will think of a solution to remove multiple collections at once
3. yes it is possible, will do it

**Comment by Dashkinru** [comment]
Hi! Thank you for your consideration and reply!

чт, 16 февр. 2023 г., 09:52 Alessandro ***@***.***>:

**Comment by a34alefeliza** [comment]
1. done
2. next in the pipeline
3. done. I've also added the possibility to switch layout (horizontal or vertical). Please have a look

**Comment by Dashkinru** [comment]
Thank you very much!

сб, 25 февр. 2023 г., 01:15 Alessandro ***@***.***>:

**Comment by Dashkinru** [comment]
Hi! I've checked the first question "Is it possible to use URL images in collection 2 pa.office?" You said you've done it, but it's still not working for me. Although I _have_ the url image in collection 2 _inside_ the collection, it fails to be displayed when it's open in the exercise.
![image](https://user-images.githubusercontent.com/66912801/221833005-12228975-e34c-434c-a4b6-66d89226932c.png)
![image](https://user-images.githubusercontent.com/66912801/221833199-76117105-91c5-4351-a756-24f53134de05.png)

In pa.findWord everything works well :) Thanks!

**Comment by a34alefeliza** [comment]
Hi Dasha,

1. so it is working as expected? I've tried on pa.office and it works for me. In case, let me know the page/collection which is not working for you and I will have a look
2. Done. On the homepage, click Quick Links > Collections. You can search any collection by name, level, or exercise. You can also filter by system or personal collections. Here you can select multiple personal collections and delete them at once. Try it and let me know what do you think, your suggestions are always appreciated.
3. Done

**Comment by Dashkinru** [comment]
Hi! 
1. It's still not working for me. I tried on DIY and Read... Have a look at DIY - Whiteboard/URL - Collection (*Whiteboard) Collection (2) *URL test. 
_BTW maybe you would add number (1) to the name Collection. And this way it'd be easier to explain to Pikimoni users where to edit: in Collection (1) or Collection (2)._ 
2. That's awesome! I have nothing to add so far. You have added a couple of useful options that make navigation so much clearer. Great thinking and great job!
3. Thanks!

**Comment by a34alefeliza** [comment]
1. fixed

**Comment by Dashkinru** [comment]
Hi! Thanks for everything! I'm closing the issue then, as it is fully and successfully completed.
